### ISSUE TITLE
Creator question group improvements

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#1]
Can we make the following improvements to the Creators Question Group (see screenshot too):

![Image](https://github.com/Rothamsted-Ecoinformatics/CKAN/assets/25688102/4ae46187-f0c2-4c63-9f62-e7544b2cff6f)

- [x] move Family name to be the first question in the group.
- [x] Have managed list of RRES staff (ideally Tegan and I can update this list. The list should have family name, given name, ORCID and affiliation
- [x] In the Family name question, CKAN should prompt suggestions as you type. Selecting an option should automatically fill the given name, ORCID and affiliation fields. But we still want to add full records manually for external collaborators.
- [x] When the Creator is added, all the information should be displayed in the list of added creators
- [x] We need an option to delete Creators who have been added in error.
- [x] This same functionality needs to be applied to the Contributor question group.

**Comment by GokulVijayakumarRam** [comment]
Assigning this back to check the tasks that are completed.
Auto filling feature with a managed list is in progress and will update once it is achieved

**Comment by richardostler** [comment]
Hi @GokulVijayakumarRam, assigning this back. Can we make it so you can chose which creator to delete - it would be frustrating to add 3 people then decide to remove the first one - you would need to delete and re-enter the last two added.

**Comment by GokulVijayakumarRam** [comment]
The required functionality is added.
Please check for the same and lt me know.

**Comment by GokulVijayakumarRam** [comment]
Managing a csv file with user information to auto-populate creator and contributor fields could cause GDPR issues and should be handled with high care. I was advised not to have any public file that holds staff information and funder information.
Please advice on this issue
Thanks
Gokul

**Comment by richardostler** [comment]
Hi @GokulVijayakumarRam, sorry but whoever advised you on that is wrong. The information is all public domain and necessary for correct citation and authorship attribution. there is no GDPR issue here. Presumably there would also be application level security so that the files used to provide this information are not directly accessible.

**Comment by GokulVijayakumarRam** [comment]
Autofill Feature for creator field is implemented.
Assigning this back to check for the same and confirm
thanks
Gokul
