### ISSUE TITLE
Resource Type Field

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [Rothamsted-Ecoinformatics/CKAN#10]
![image](https://github.com/Rothamsted-Ecoinformatics/CKAN/assets/157587419/ea2cc28e-5a02-49ae-9bce-7dcb42be7ad3)

Renamed and Sorted the spacing as per the requirements
Assigning this to check for the same and confirm

Thanks
gokul

**Comment by richardostler** [comment]
Perfect, thanks
