### ISSUE TITLE
Keywords Field

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [Rothamsted-Ecoinformatics/CKAN#13]
![image](https://github.com/user-attachments/assets/d1bf0883-0236-4506-a7f8-1c90062be10a)

Keywords field is configured as per the requirements
It is duplicated with tags. i.e. the keywords entered in the field will be considered as tags and the tag field is hidden

**Comment by richardostler** [comment]
Looks good although reviewing the source code for a published dataset (just created) the @dastset/schema JSON is missing this info - there are other issues with that JSON so will raise as a separate issue.
