### ISSUE TITLE
Resource Data Management Field

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [Rothamsted-Ecoinformatics/CKAN#14]
![image](https://github.com/user-attachments/assets/ef811b5e-1ba3-4bd6-a793-c475385d2730)

Resource data management section is added as per the requirements
Assigning this to check for the same and confirm

**Comment by richardostler** [comment]
Looks good, just noticed one option is missing - please can you add 'Metabolomics Facility' after 'Lipidomics Facility'. You can close once added.

**Comment by GokulVijayakumarRam** [comment]
Metabolomics Facility is added.
closing the ticket
