### ISSUE TITLE
Bug with ResourceTypeGeneral

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#15]
There is a bug with resourceTypeGeneral. If you leave the default option 'Dataset' you get a missing value error. To submit you have to change from the 'Dataset' option, then reselect the dataset option for it to be selected.

**Comment by GokulVijayakumarRam** [comment]
this bug is fixed
assigning this back to check for the same and confirm

thanks
gokul

**Comment by richardostler** [comment]
tested and works, thanks
