### ISSUE TITLE
Data file citations

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#16]
See [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ni9UcmVlTm9kZS8zMTM3MDcxMDU4fDcyLjY=) for enhancements and corrections to data file citations, taken from this [test dataset](http://pursuit.rothamsted.ac.uk/dataset/some-data)

**Comment by GokulVijayakumarRam** [comment]
The requirements mentioned in the screenshot is configured
Assigning this to check for the same and confirm
thanks
Gokul

**Comment by richardostler** [comment]
Looks good
