### ISSUE TITLE
Data file licence

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#17]
On the data file view page there is an option for the data licence. This should, by default, be the same as the licence applied to the dataset but instead says 'No Licence Provided' See [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ni9UcmVlTm9kZS8zMTM3MDcxMDU4fDcyLjY=) for enhancements and corrections to data file citations, taken from this [test dataset](http://pursuit.rothamsted.ac.uk/dataset/some-data). I also cannot see where this licence might be edited from?

**Comment by GokulVijayakumarRam** [comment]
This is the same license users give when creating the dataset
The data file view page is configure to show this license.

Assigning this to check for the same and confirm

Thanks 
Gokul
