### ISSUE TITLE
View data file page enhancements

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#18]
A couple of minor enhancements to the data view page below and see [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ni9UcmVlTm9kZS8zMTM3MDcxMDU4fDcyLjY=), taken from this [test dataset](http://pursuit.rothamsted.ac.uk/dataset/some-data)

- [x] Remove _>>>>>>Head_ text
- [x] Update twitter to X
- [x] Add LinkedIn to socials

**Comment by GokulVijayakumarRam** [comment]
The required changes are configured
Assigning this to check for the same and confirm

Thanks
Gokul

**Comment by richardostler** [comment]
Perfect thanks
