### ISSUE TITLE
Dataset view page - licence info

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#19]
On the dataset view page, make the following changes for licence info. See also [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ny9UcmVlTm9kZS8zMTI3MTExNTY3fDcyLjY=) and the [source page](http://pursuit.rothamsted.ac.uk/dataset/some-data)

- [x] Group the licence information under the 'lock' icon
- [x] Remove the 'No licence provided' text
- [x] Use the following text: 'This work is licensed under Creative Commons Attribution 4.0 International.' 
- [x] The licence must link to the legal code, e.g. for CC-BY: https://creativecommons.org/licenses/by/4.0/legalcode
- [x] After the legal code add the relevant CC icons - [https://chooser-beta.creativecommons.org/](see for an example)

**Comment by GokulVijayakumarRam** [comment]
the required changes are configured
Assigning this to check for the same and confirm
Thanks
Gokul

**Comment by richardostler** [comment]
Perfect thanks

**Comment by richardostler** [comment]
Sorry just notice one really minor thing. Can you move the licence lock image and text under the line
![image](https://github.com/user-attachments/assets/9872f630-f39c-4cf5-97e2-6a166585aa90)

**Comment by richardostler** [comment]
And replace the icons with the ones from this page https://creativecommons.org/mission/downloads/ - these ones are transparent. If you can make them inline with the text and size accordingly. i.e. a little bit smaller

**Comment by GokulVijayakumarRam** [comment]
![image](https://github.com/user-attachments/assets/d4eb383a-1709-4c00-b05d-d4355c31f88c)

The mentioned changes are made on the license field
Assigning this to check for the same and confirm

Thanks
Gokul

**Comment by richardostler** [comment]
Perfect, thanks
