### ISSUE TITLE
Usability enhancements - use radio buttons

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#2]
Good U/X is to prefer radio buttons to drop down select lists for short choice groups, so can the following be converted to radio buttons:
- [x] Experiment Code
- [x] Resource Type
- [x] Licence
- [x] Research Infrastructure Used

**Comment by GokulVijayakumarRam** [comment]
The required changes are applied.
Assigning this back to check for the same and confirm
Thanks 
Gokul
