### ISSUE TITLE
Dataset view page remove grey line separators and text backgrounds

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#20]
See items 1, 6, 7 on  [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ny9UcmVlTm9kZS8zMTI3MTExNTY3fDcyLjY=) and the [source page](http://pursuit.rothamsted.ac.uk/dataset/some-data)

- [x] On the dataset view page remove grey line separators
- [x] Remove grey backgrounds for text
- [x] for the left column, left justify text

**Comment by GokulVijayakumarRam** [comment]
Removed all grey lines
Assigning this back to check for the same and confirm

**Comment by richardostler** [comment]
Perfect, thanks
