### ISSUE TITLE
Move and replace subjects

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#21]
The subjects are show in two places, see item 4 on [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ny9UcmVlTm9kZS8zMTI3MTExNTY3fDcyLjY=) and the [source page](http://pursuit.rothamsted.ac.uk/dataset/some-data). Can we:

- [x] delete the subjects text from the left part of the screen 
- [x] Move the hyperlinked subject boxes to the left part of the screen in place of the previous text (preserve the boxes and linking)

**Comment by GokulVijayakumarRam** [comment]
The mentioned requirements are configured
Assigning this back to check for the same and confirm
Thanks
Gokul
