### ISSUE TITLE
Dataset view page enhancements to lists and tables

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#22]
We want to reformat lists and tables to improve page display, see items 5, 9, 10 and 11 on [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ny9UcmVlTm9kZS8zMTI3MTExNTY3fDcyLjY=) and the [source page](http://pursuit.rothamsted.ac.uk/dataset/some-data)

- [x] ORCIDs when provided should link to the authors external ORCID profile
- [x] Reformat Funder Information and Contributors as tables
- [x] Reformat Related Resources as a list showing only the link 
- [x] Tables should be formatted so that the column headers use the same green as the page banner and text is white for contrast. Table rows should have white background colour. Not alternating colour strips.

**Comment by GokulVijayakumarRam** [comment]
The mentioned changes are made.
Assigning this to check for the same and confirm

Thanks
Gokul
