### ISSUE TITLE
Dataset view page Left column enhancements 

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#23]
See also items 3 and 8 [LabArchives Screenshot](https://uk-mynotebook.labarchives.com/share/CKAN%2520Project/MjguNnwyNjY0OC8yMi04Ny9UcmVlTm9kZS8zMTI3MTExNTY3fDcyLjY=) and the [source page](http://pursuit.rothamsted.ac.uk/dataset/some-data)

- [x] Only show date labels if there is a corresponding date value
- [x] Remove the heading 'Other dates', instead use date labels as headings if a date value exists
- [x] Remove the heading 'Publisher Information, instead use 'Publisher' and ' Publication Year' as headings
- [x] Remove the heading 'Resource Type Information', instead use 'General Resource Type' and 'Resource Type'

**Comment by GokulVijayakumarRam** [comment]
The mentioned requirements are configured.
Assigning this to check for the same and confirm
Thanks
Gokul

**Comment by richardostler** [comment]
Perfect, thanks
