### ISSUE TITLE
Formatting authors in citations

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#24]
For the recommended citations can we change the formatting for authors to be 'Lastname Initials'

e.g. [http://pursuit.rothamsted.ac.uk/dataset/some-data](http://pursuit.rothamsted.ac.uk/dataset/some-data) currently has 'Richard Ostler,Margaret Glendining (2024).'

This should be : 'Ostler R. and Glendining M. 2024

[http://pursuit.rothamsted.ac.uk/dataset/emi-drapers-transition-experiment](http://pursuit.rothamsted.ac.uk/dataset/emi-drapers-transition-experiment) 'Marcelo Valadares Galdos (2024)' becomes 'Galdos M. V. 2024

 [http://pursuit.rothamsted.ac.uk/dataset/yet-another-test-dataset](http://pursuit.rothamsted.ac.uk/dataset/yet-another-test-dataset) 'Margaret Glendining,Sarah Perryman,Richard Ostler (2024)' becomes 'Glendining M., Perryman S. and Ostler R. 2024

Note the spacings between words and periods after initials.

**Comment by GokulVijayakumarRam** [comment]
![image](https://github.com/user-attachments/assets/bb4ec736-540a-464a-82e2-f601610e6b57)

The citation field is edited as per the requirement
Assigning this to check for the same and confirm
Thanks
Gokul

**Comment by richardostler** [comment]
Almost there... a couple of issues:
1. see following image: 
![image](https://github.com/user-attachments/assets/5a93eecf-ba81-42b3-9080-9712406ac7d7)

2. If only one author, it is being prefixed with 'and'. (see following image)
![image](https://github.com/user-attachments/assets/84c82875-7f25-4467-b813-877f62c14e4b)

**Comment by GokulVijayakumarRam** [comment]
The "and" getting prefixed is fixed
![image](https://github.com/user-attachments/assets/5284210d-cffd-4a48-86ad-a4614cc73a1c)

Changed the spacing issues
![image](https://github.com/user-attachments/assets/bf331136-4ae0-4ebd-9fcb-87527f55e07c)

Assigning this to check for the same and confirm
thanks

**Comment by richardostler** [comment]
Perfect! thanks
