### ISSUE TITLE
Conditional DOI Minting

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [Rothamsted-Ecoinformatics/CKAN#29]
Doi are supposed to be generated only if user havent provided one

**Comment by GokulVijayakumarRam** [comment]
Hi Richard
An additional field is provided in the dataset creation page to add DOIs if it already exists
If doi provided while creating the dataset, that doi will be used, else new doi will be minted

PS: the site is still using the fake doi
Once the testing is completed we could change that to the real one

Assigning this to check for the same and confirm

Thanks
Gokul

**Comment by GokulVijayakumarRam** [comment]
Just remembered that you wont have a login in https://data.rothamsted.ac.uk

The  same changes are made in pursuit as well. You will be able to test it on pursuit.
I'd wait for the SSO to kick in before registering in  https://data.rothamsted.ac.uk

Thanks 
Gokul

**Comment by richardostler** [comment]
Thanks Gokul, I'll take a look
