### ISSUE TITLE
Update Resource Types

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#3]
We don't need to use the full set of General Resource Types, so can we use the following shortened list:

Dataset
Instrument
Model
Software
Image
AudioVisual
ComputationalNotebook.

If possible can the display versions use correct spacing, but what what appears in the machine readable metadata is displayed as above.

**Comment by GokulVijayakumarRam** [comment]
General Resource Type field is updated with only the given values
