### ISSUE TITLE
Map Bounding Box fix

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [Rothamsted-Ecoinformatics/CKAN#31]
Fix the map bounding box and its display

**Comment by GokulVijayakumarRam** [comment]
Map issue on the View page is fixed
Working on the dataset add page

**Comment by GokulVijayakumarRam** [comment]
map issue on the dataset add page is also fixed
Assigning this to check for the same 
Thanks Gokul

**Comment by richardostler** [comment]
Thanks @GokulVijayakumarRam , its almost there. The point location should be hidden (just to tidy things up, if there is no location:

![image](https://github.com/user-attachments/assets/79535c8a-50f7-4495-a9c9-1134ffc6618c)

**Comment by GokulVijayakumarRam** [comment]
![image](https://github.com/user-attachments/assets/0d8112d4-494e-4e08-8613-2be9e7f9857f)

the required changes are commited to the website
Please check for the same and confirm

Thanks 
Gokul

**Comment by richardostler** [comment]
thanks
