### ISSUE TITLE
Funder information question group improvements

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/CKAN#4]
Can we make the following enhancements to the funder information question group (see screenshot also).

![Image](https://github.com/Rothamsted-Ecoinformatics/CKAN/assets/25688102/9eaa7ce9-7600-4b96-ac4f-ad325c4451bf)

- [x] Funder Identifier and Funder ID type should be hidden from the user - these are linked properties of the Funder name which should be visible
- [x] Funder Identifier and Funder ID **must** be part of the machine readable metadata as per DataCite schema specification.
- [x] Award number should be the first item in the question group
- [x] Award title should be the second item in the question group
- [x] Typing an award number or award title should start to prompt the user with matching options from a list. The user should be able to select a matching option and this should auto fill the question group items (award title, award number, award URI, funder Name).
- [x] The added awards should display as a list with all the information entered visible
- [x] It should be possible to add awards added in error.

**Comment by GokulVijayakumarRam** [comment]
The mentioned changes are incorporated. Please check for the same and let me know.
As mentioned for the creator information, I was advised not to have funder information in a public file to facilitate the auto-fill requirement.
Please advice on the same.
thanks
Gokul

**Comment by GokulVijayakumarRam** [comment]
Auto filling funder information is configured.
Please check for the same and confirm

**Comment by GokulVijayakumarRam** [comment]
Assigning this back to make the modification

**Comment by GokulVijayakumarRam** [comment]
All the fields for the funders will be auto-filled if the award number is selected.

More awards and funder information should be added to this csv file.

https://github.com/Rothamsted-Ecoinformatics/CKAN/blob/master/src/csvFiles/funderTotal_info.csv

**Comment by GokulVijayakumarRam** [comment]
Assigning this to check for the auto-fill functionality

Thanks
Gokul
