### ISSUE TITLE
Author Field 

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [Rothamsted-Ecoinformatics/CKAN#8]
![image](https://github.com/Rothamsted-Ecoinformatics/CKAN/assets/157587419/a7613fdd-73c6-4987-b240-06e01b4e0925)

The author field is setup as per the requirement.
Assigning this ticket to check for the same and confirm.

Thanks
Gokul

**Comment by richardostler** [comment]
Perfect, thanks
