### ISSUE TITLE
Contributor Field

### ISSUE THREAD

**Issue by GokulVijayakumarRam** [Rothamsted-Ecoinformatics/CKAN#9]
![image](https://github.com/Rothamsted-Ecoinformatics/CKAN/assets/157587419/baf3074d-83dd-4196-8c2f-e1c539ddfb49)

Moved to after Author Field
Setup same as authors
Assigning this to check for the same and confirm

Thanks 
Gokul

**Comment by richardostler** [comment]
Perfect, thanks
